# escape=`
# Archivo Dockerfile del reto3

#creamos el contenedor v.1.0

# partimos del la version alpine
FROM nginx:alpine

# copiamos el archivo de nuestro local
COPY index.html /usr/share/nginx/html

#el puerto para la img
EXPOSE 82

#imprime en la terminal
RUN echo "Creando Mi 1era Img desde cero!!!"
